name: gtsrb
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch=1.7.0
  - torchvision=0.8.0
  - torchaudio=0.7.0
  - cudatoolkit=11.0
  - pytorch-lightning=1.1.0
  - tensorboard=2.14.0
  - numpy=1.24.2
  - protobuf=3.20.3
  - requests
  - tqdm
  - pip
  - pip:
      - wandb
